# Generated by Django 4.0.5 on 2022-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempratue', models.IntegerField(blank=True, null=True, verbose_name='دمای خانه')),
                ('pir', models.BooleanField(blank=True, null=True, verbose_name='وضعیت سنسور حرکت')),
                ('ldr', models.IntegerField(blank=True, null=True, verbose_name='میزان نور')),
            ],
        ),
        migrations.CreateModel(
            name='ServerStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lamp', models.BooleanField(blank=True, null=True, verbose_name='لامپ')),
                ('relay2', models.BooleanField(blank=True, null=True, verbose_name='رله شماره دو')),
            ],
        ),
    ]
