# Generated by Django 4.0.5 on 2022-06-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday', '0002_rename_homestation_homeside_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeside',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='serverside',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
    ]
