# Generated by Django 4.0.5 on 2022-06-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday', '0003_homeside_date_serverside_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeside',
            name='humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='رطوبت'),
        ),
    ]
