# Generated by Django 4.0.5 on 2022-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friday', '0004_homeside_humidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverside',
            name='alert_mode',
            field=models.BooleanField(blank=True, null=True, verbose_name='حالت هشدار دهی'),
        ),
    ]
